[build]
  command = "npm run build"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[functions]
  timeout = 30

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"